name: Jym
description: A workout planner
version: 0.0.1
homepage: https://github.com/cybaker/jym
repository: https://github.com/cybaker/jym

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.2.2
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  intl: ^0.18.1
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
