name: flutter_jym
description: A workout planner
version: 0.0.1
homepage: https://github.com/cybaker/flutter_jym
repository: https://github.com/cybaker/flutter_jym

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.2.2
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
